### ISSUE TITLE
extension API Discussion

### ISSUE THREAD

**Issue by rmanibus** [quarkiverse/quarkus-bucket4j#2]
This issue is a thread for polishing the extension API

here is a first draft of the API that would be exposed by this extension:

```yaml
quarkus:
  rate-limiter:
    limits:
      group1:
        burst-protection:
          max-usage: 10
          duration: 1S
        fair-use:
          max-usage: 100
          duration: 5m
```
```java
@RateLimited(limitsKey = "group1")
void limitedMethod()
```
if multiple methods share the same limits key, user should be able to either share or isolate buckets for those methods.

Segmentation Key:
- UNSEGMENTED: the limit is shared for all the incoming trafic
- SEGMENT_BY_IP: one bucket is created per IP address, should throw if request context is not enabled
- CUSTOM: should allow a user defined segmentation method, working with CDI (use case: segment by user id)

Bucket registry:
Local for now, but network registry should be supported in the future (hazelcast, redis ...)

**Comment by rmanibus** [comment]
@melloware, I pushed the first commit, you can use this thread for API related discussions

**Comment by rmanibus** [comment]
I would prefer the configuration to look like
```
quarkus:
  rate-limiter:
    limits:
      group1:
        - name: burst-protection
          max-usage: 10
          duration: 1S
        - name: fair-use
          max-usage: 100
          duration: 5m
```
but when I try to use a List instead of a map, I have an exception saying it did not find any transformer for my nested config group.
Does someone have any idea how I could achieve this ?
